# Generated by Django 2.1.7 on 2019-04-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Надо сделать', 'Надо сделать'), ('Сделано', 'Сделано'), ('Отменено', 'Отменено')], default='Надо сделать', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
